import Head from "next/head";
import Footer from "../components/Footer";
import NavBar from "../components/NavBar";
import "../styles/globals.css";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>In loving memory of Mujoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <Component {...pageProps} />
      <Footer />
    </>
  );
}

export default MyApp;
